// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: page.proto

package sorts.mediawiki;

public final class MediawikiPage {
  private MediawikiPage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required uint64 id = 1;
    /**
     * <code>required uint64 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required uint64 id = 1;</code>
     */
    long getId();

    // optional .sorts.mediawiki.Page.Revision revision = 2;
    /**
     * <code>optional .sorts.mediawiki.Page.Revision revision = 2;</code>
     */
    boolean hasRevision();
    /**
     * <code>optional .sorts.mediawiki.Page.Revision revision = 2;</code>
     */
    sorts.mediawiki.MediawikiPage.Page.Revision getRevision();
    /**
     * <code>optional .sorts.mediawiki.Page.Revision revision = 2;</code>
     */
    sorts.mediawiki.MediawikiPage.Page.RevisionOrBuilder getRevisionOrBuilder();
  }
  /**
   * Protobuf type {@code sorts.mediawiki.Page}
   */
  public static final class Page extends
      com.google.protobuf.GeneratedMessage
      implements PageOrBuilder {
    // Use Page.newBuilder() to construct.
    private Page(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Page(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Page defaultInstance;
    public static Page getDefaultInstance() {
      return defaultInstance;
    }

    public Page getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Page(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readUInt64();
              break;
            }
            case 18: {
              sorts.mediawiki.MediawikiPage.Page.Revision.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = revision_.toBuilder();
              }
              revision_ = input.readMessage(sorts.mediawiki.MediawikiPage.Page.Revision.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(revision_);
                revision_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sorts.mediawiki.MediawikiPage.internal_static_sorts_mediawiki_Page_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sorts.mediawiki.MediawikiPage.internal_static_sorts_mediawiki_Page_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              sorts.mediawiki.MediawikiPage.Page.class, sorts.mediawiki.MediawikiPage.Page.Builder.class);
    }

    public static com.google.protobuf.Parser<Page> PARSER =
        new com.google.protobuf.AbstractParser<Page>() {
      public Page parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Page(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Page> getParserForType() {
      return PARSER;
    }

    public interface RevisionOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // required uint64 id = 1;
      /**
       * <code>required uint64 id = 1;</code>
       */
      boolean hasId();
      /**
       * <code>required uint64 id = 1;</code>
       */
      long getId();

      // required string timestamp = 2;
      /**
       * <code>required string timestamp = 2;</code>
       */
      boolean hasTimestamp();
      /**
       * <code>required string timestamp = 2;</code>
       */
      java.lang.String getTimestamp();
      /**
       * <code>required string timestamp = 2;</code>
       */
      com.google.protobuf.ByteString
          getTimestampBytes();

      // optional .sorts.mediawiki.Page.Revision.Contributor contributor = 3;
      /**
       * <code>optional .sorts.mediawiki.Page.Revision.Contributor contributor = 3;</code>
       */
      boolean hasContributor();
      /**
       * <code>optional .sorts.mediawiki.Page.Revision.Contributor contributor = 3;</code>
       */
      sorts.mediawiki.MediawikiPage.Page.Revision.Contributor getContributor();
      /**
       * <code>optional .sorts.mediawiki.Page.Revision.Contributor contributor = 3;</code>
       */
      sorts.mediawiki.MediawikiPage.Page.Revision.ContributorOrBuilder getContributorOrBuilder();

      // optional bool minor = 4;
      /**
       * <code>optional bool minor = 4;</code>
       */
      boolean hasMinor();
      /**
       * <code>optional bool minor = 4;</code>
       */
      boolean getMinor();
    }
    /**
     * Protobuf type {@code sorts.mediawiki.Page.Revision}
     */
    public static final class Revision extends
        com.google.protobuf.GeneratedMessage
        implements RevisionOrBuilder {
      // Use Revision.newBuilder() to construct.
      private Revision(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private Revision(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final Revision defaultInstance;
      public static Revision getDefaultInstance() {
        return defaultInstance;
      }

      public Revision getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private Revision(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 8: {
                bitField0_ |= 0x00000001;
                id_ = input.readUInt64();
                break;
              }
              case 18: {
                bitField0_ |= 0x00000002;
                timestamp_ = input.readBytes();
                break;
              }
              case 26: {
                sorts.mediawiki.MediawikiPage.Page.Revision.Contributor.Builder subBuilder = null;
                if (((bitField0_ & 0x00000004) == 0x00000004)) {
                  subBuilder = contributor_.toBuilder();
                }
                contributor_ = input.readMessage(sorts.mediawiki.MediawikiPage.Page.Revision.Contributor.PARSER, extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom(contributor_);
                  contributor_ = subBuilder.buildPartial();
                }
                bitField0_ |= 0x00000004;
                break;
              }
              case 32: {
                bitField0_ |= 0x00000008;
                minor_ = input.readBool();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return sorts.mediawiki.MediawikiPage.internal_static_sorts_mediawiki_Page_Revision_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return sorts.mediawiki.MediawikiPage.internal_static_sorts_mediawiki_Page_Revision_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                sorts.mediawiki.MediawikiPage.Page.Revision.class, sorts.mediawiki.MediawikiPage.Page.Revision.Builder.class);
      }

      public static com.google.protobuf.Parser<Revision> PARSER =
          new com.google.protobuf.AbstractParser<Revision>() {
        public Revision parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Revision(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<Revision> getParserForType() {
        return PARSER;
      }

      public interface ContributorOrBuilder
          extends com.google.protobuf.MessageOrBuilder {

        // optional string username = 1;
        /**
         * <code>optional string username = 1;</code>
         */
        boolean hasUsername();
        /**
         * <code>optional string username = 1;</code>
         */
        java.lang.String getUsername();
        /**
         * <code>optional string username = 1;</code>
         */
        com.google.protobuf.ByteString
            getUsernameBytes();

        // optional uint64 id = 2;
        /**
         * <code>optional uint64 id = 2;</code>
         */
        boolean hasId();
        /**
         * <code>optional uint64 id = 2;</code>
         */
        long getId();
      }
      /**
       * Protobuf type {@code sorts.mediawiki.Page.Revision.Contributor}
       */
      public static final class Contributor extends
          com.google.protobuf.GeneratedMessage
          implements ContributorOrBuilder {
        // Use Contributor.newBuilder() to construct.
        private Contributor(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
          super(builder);
          this.unknownFields = builder.getUnknownFields();
        }
        private Contributor(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

        private static final Contributor defaultInstance;
        public static Contributor getDefaultInstance() {
          return defaultInstance;
        }

        public Contributor getDefaultInstanceForType() {
          return defaultInstance;
        }

        private final com.google.protobuf.UnknownFieldSet unknownFields;
        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
            getUnknownFields() {
          return this.unknownFields;
        }
        private Contributor(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          initFields();
          int mutable_bitField0_ = 0;
          com.google.protobuf.UnknownFieldSet.Builder unknownFields =
              com.google.protobuf.UnknownFieldSet.newBuilder();
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!parseUnknownField(input, unknownFields,
                                         extensionRegistry, tag)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  bitField0_ |= 0x00000001;
                  username_ = input.readBytes();
                  break;
                }
                case 16: {
                  bitField0_ |= 0x00000002;
                  id_ = input.readUInt64();
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
          } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this);
          } finally {
            this.unknownFields = unknownFields.build();
            makeExtensionsImmutable();
          }
        }
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return sorts.mediawiki.MediawikiPage.internal_static_sorts_mediawiki_Page_Revision_Contributor_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return sorts.mediawiki.MediawikiPage.internal_static_sorts_mediawiki_Page_Revision_Contributor_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  sorts.mediawiki.MediawikiPage.Page.Revision.Contributor.class, sorts.mediawiki.MediawikiPage.Page.Revision.Contributor.Builder.class);
        }

        public static com.google.protobuf.Parser<Contributor> PARSER =
            new com.google.protobuf.AbstractParser<Contributor>() {
          public Contributor parsePartialFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
            return new Contributor(input, extensionRegistry);
          }
        };

        @java.lang.Override
        public com.google.protobuf.Parser<Contributor> getParserForType() {
          return PARSER;
        }

        private int bitField0_;
        // optional string username = 1;
        public static final int USERNAME_FIELD_NUMBER = 1;
        private java.lang.Object username_;
        /**
         * <code>optional string username = 1;</code>
         */
        public boolean hasUsername() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>optional string username = 1;</code>
         */
        public java.lang.String getUsername() {
          java.lang.Object ref = username_;
          if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
          } else {
            com.google.protobuf.ByteString bs = 
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              username_ = s;
            }
            return s;
          }
        }
        /**
         * <code>optional string username = 1;</code>
         */
        public com.google.protobuf.ByteString
            getUsernameBytes() {
          java.lang.Object ref = username_;
          if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            username_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }

        // optional uint64 id = 2;
        public static final int ID_FIELD_NUMBER = 2;
        private long id_;
        /**
         * <code>optional uint64 id = 2;</code>
         */
        public boolean hasId() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>optional uint64 id = 2;</code>
         */
        public long getId() {
          return id_;
        }

        private void initFields() {
          username_ = "";
          id_ = 0L;
        }
        private byte memoizedIsInitialized = -1;
        public final boolean isInitialized() {
          byte isInitialized = memoizedIsInitialized;
          if (isInitialized != -1) return isInitialized == 1;

          memoizedIsInitialized = 1;
          return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                            throws java.io.IOException {
          getSerializedSize();
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            output.writeBytes(1, getUsernameBytes());
          }
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            output.writeUInt64(2, id_);
          }
          getUnknownFields().writeTo(output);
        }

        private int memoizedSerializedSize = -1;
        public int getSerializedSize() {
          int size = memoizedSerializedSize;
          if (size != -1) return size;

          size = 0;
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            size += com.google.protobuf.CodedOutputStream
              .computeBytesSize(1, getUsernameBytes());
          }
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            size += com.google.protobuf.CodedOutputStream
              .computeUInt64Size(2, id_);
          }
          size += getUnknownFields().getSerializedSize();
          memoizedSerializedSize = size;
          return size;
        }

        private static final long serialVersionUID = 0L;
        @java.lang.Override
        protected java.lang.Object writeReplace()
            throws java.io.ObjectStreamException {
          return super.writeReplace();
        }

        public static sorts.mediawiki.MediawikiPage.Page.Revision.Contributor parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return PARSER.parseFrom(data);
        }
        public static sorts.mediawiki.MediawikiPage.Page.Revision.Contributor parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return PARSER.parseFrom(data, extensionRegistry);
        }
        public static sorts.mediawiki.MediawikiPage.Page.Revision.Contributor parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return PARSER.parseFrom(data);
        }
        public static sorts.mediawiki.MediawikiPage.Page.Revision.Contributor parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return PARSER.parseFrom(data, extensionRegistry);
        }
        public static sorts.mediawiki.MediawikiPage.Page.Revision.Contributor parseFrom(java.io.InputStream input)
            throws java.io.IOException {
          return PARSER.parseFrom(input);
        }
        public static sorts.mediawiki.MediawikiPage.Page.Revision.Contributor parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          return PARSER.parseFrom(input, extensionRegistry);
        }
        public static sorts.mediawiki.MediawikiPage.Page.Revision.Contributor parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
          return PARSER.parseDelimitedFrom(input);
        }
        public static sorts.mediawiki.MediawikiPage.Page.Revision.Contributor parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          return PARSER.parseDelimitedFrom(input, extensionRegistry);
        }
        public static sorts.mediawiki.MediawikiPage.Page.Revision.Contributor parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
          return PARSER.parseFrom(input);
        }
        public static sorts.mediawiki.MediawikiPage.Page.Revision.Contributor parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          return PARSER.parseFrom(input, extensionRegistry);
        }

        public static Builder newBuilder() { return Builder.create(); }
        public Builder newBuilderForType() { return newBuilder(); }
        public static Builder newBuilder(sorts.mediawiki.MediawikiPage.Page.Revision.Contributor prototype) {
          return newBuilder().mergeFrom(prototype);
        }
        public Builder toBuilder() { return newBuilder(this); }

        @java.lang.Override
        protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          Builder builder = new Builder(parent);
          return builder;
        }
        /**
         * Protobuf type {@code sorts.mediawiki.Page.Revision.Contributor}
         */
        public static final class Builder extends
            com.google.protobuf.GeneratedMessage.Builder<Builder>
           implements sorts.mediawiki.MediawikiPage.Page.Revision.ContributorOrBuilder {
          public static final com.google.protobuf.Descriptors.Descriptor
              getDescriptor() {
            return sorts.mediawiki.MediawikiPage.internal_static_sorts_mediawiki_Page_Revision_Contributor_descriptor;
          }

          protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
              internalGetFieldAccessorTable() {
            return sorts.mediawiki.MediawikiPage.internal_static_sorts_mediawiki_Page_Revision_Contributor_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                    sorts.mediawiki.MediawikiPage.Page.Revision.Contributor.class, sorts.mediawiki.MediawikiPage.Page.Revision.Contributor.Builder.class);
          }

          // Construct using sorts.mediawiki.MediawikiPage.Page.Revision.Contributor.newBuilder()
          private Builder() {
            maybeForceBuilderInitialization();
          }

          private Builder(
              com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
          }
          private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
            }
          }
          private static Builder create() {
            return new Builder();
          }

          public Builder clear() {
            super.clear();
            username_ = "";
            bitField0_ = (bitField0_ & ~0x00000001);
            id_ = 0L;
            bitField0_ = (bitField0_ & ~0x00000002);
            return this;
          }

          public Builder clone() {
            return create().mergeFrom(buildPartial());
          }

          public com.google.protobuf.Descriptors.Descriptor
              getDescriptorForType() {
            return sorts.mediawiki.MediawikiPage.internal_static_sorts_mediawiki_Page_Revision_Contributor_descriptor;
          }

          public sorts.mediawiki.MediawikiPage.Page.Revision.Contributor getDefaultInstanceForType() {
            return sorts.mediawiki.MediawikiPage.Page.Revision.Contributor.getDefaultInstance();
          }

          public sorts.mediawiki.MediawikiPage.Page.Revision.Contributor build() {
            sorts.mediawiki.MediawikiPage.Page.Revision.Contributor result = buildPartial();
            if (!result.isInitialized()) {
              throw newUninitializedMessageException(result);
            }
            return result;
          }

          public sorts.mediawiki.MediawikiPage.Page.Revision.Contributor buildPartial() {
            sorts.mediawiki.MediawikiPage.Page.Revision.Contributor result = new sorts.mediawiki.MediawikiPage.Page.Revision.Contributor(this);
            int from_bitField0_ = bitField0_;
            int to_bitField0_ = 0;
            if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
              to_bitField0_ |= 0x00000001;
            }
            result.username_ = username_;
            if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
              to_bitField0_ |= 0x00000002;
            }
            result.id_ = id_;
            result.bitField0_ = to_bitField0_;
            onBuilt();
            return result;
          }

          public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof sorts.mediawiki.MediawikiPage.Page.Revision.Contributor) {
              return mergeFrom((sorts.mediawiki.MediawikiPage.Page.Revision.Contributor)other);
            } else {
              super.mergeFrom(other);
              return this;
            }
          }

          public Builder mergeFrom(sorts.mediawiki.MediawikiPage.Page.Revision.Contributor other) {
            if (other == sorts.mediawiki.MediawikiPage.Page.Revision.Contributor.getDefaultInstance()) return this;
            if (other.hasUsername()) {
              bitField0_ |= 0x00000001;
              username_ = other.username_;
              onChanged();
            }
            if (other.hasId()) {
              setId(other.getId());
            }
            this.mergeUnknownFields(other.getUnknownFields());
            return this;
          }

          public final boolean isInitialized() {
            return true;
          }

          public Builder mergeFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
            sorts.mediawiki.MediawikiPage.Page.Revision.Contributor parsedMessage = null;
            try {
              parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
              parsedMessage = (sorts.mediawiki.MediawikiPage.Page.Revision.Contributor) e.getUnfinishedMessage();
              throw e;
            } finally {
              if (parsedMessage != null) {
                mergeFrom(parsedMessage);
              }
            }
            return this;
          }
          private int bitField0_;

          // optional string username = 1;
          private java.lang.Object username_ = "";
          /**
           * <code>optional string username = 1;</code>
           */
          public boolean hasUsername() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
          }
          /**
           * <code>optional string username = 1;</code>
           */
          public java.lang.String getUsername() {
            java.lang.Object ref = username_;
            if (!(ref instanceof java.lang.String)) {
              java.lang.String s = ((com.google.protobuf.ByteString) ref)
                  .toStringUtf8();
              username_ = s;
              return s;
            } else {
              return (java.lang.String) ref;
            }
          }
          /**
           * <code>optional string username = 1;</code>
           */
          public com.google.protobuf.ByteString
              getUsernameBytes() {
            java.lang.Object ref = username_;
            if (ref instanceof String) {
              com.google.protobuf.ByteString b = 
                  com.google.protobuf.ByteString.copyFromUtf8(
                      (java.lang.String) ref);
              username_ = b;
              return b;
            } else {
              return (com.google.protobuf.ByteString) ref;
            }
          }
          /**
           * <code>optional string username = 1;</code>
           */
          public Builder setUsername(
              java.lang.String value) {
            if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
            username_ = value;
            onChanged();
            return this;
          }
          /**
           * <code>optional string username = 1;</code>
           */
          public Builder clearUsername() {
            bitField0_ = (bitField0_ & ~0x00000001);
            username_ = getDefaultInstance().getUsername();
            onChanged();
            return this;
          }
          /**
           * <code>optional string username = 1;</code>
           */
          public Builder setUsernameBytes(
              com.google.protobuf.ByteString value) {
            if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
            username_ = value;
            onChanged();
            return this;
          }

          // optional uint64 id = 2;
          private long id_ ;
          /**
           * <code>optional uint64 id = 2;</code>
           */
          public boolean hasId() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
          }
          /**
           * <code>optional uint64 id = 2;</code>
           */
          public long getId() {
            return id_;
          }
          /**
           * <code>optional uint64 id = 2;</code>
           */
          public Builder setId(long value) {
            bitField0_ |= 0x00000002;
            id_ = value;
            onChanged();
            return this;
          }
          /**
           * <code>optional uint64 id = 2;</code>
           */
          public Builder clearId() {
            bitField0_ = (bitField0_ & ~0x00000002);
            id_ = 0L;
            onChanged();
            return this;
          }

          // @@protoc_insertion_point(builder_scope:sorts.mediawiki.Page.Revision.Contributor)
        }

        static {
          defaultInstance = new Contributor(true);
          defaultInstance.initFields();
        }

        // @@protoc_insertion_point(class_scope:sorts.mediawiki.Page.Revision.Contributor)
      }

      private int bitField0_;
      // required uint64 id = 1;
      public static final int ID_FIELD_NUMBER = 1;
      private long id_;
      /**
       * <code>required uint64 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint64 id = 1;</code>
       */
      public long getId() {
        return id_;
      }

      // required string timestamp = 2;
      public static final int TIMESTAMP_FIELD_NUMBER = 2;
      private java.lang.Object timestamp_;
      /**
       * <code>required string timestamp = 2;</code>
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string timestamp = 2;</code>
       */
      public java.lang.String getTimestamp() {
        java.lang.Object ref = timestamp_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            timestamp_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string timestamp = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTimestampBytes() {
        java.lang.Object ref = timestamp_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          timestamp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      // optional .sorts.mediawiki.Page.Revision.Contributor contributor = 3;
      public static final int CONTRIBUTOR_FIELD_NUMBER = 3;
      private sorts.mediawiki.MediawikiPage.Page.Revision.Contributor contributor_;
      /**
       * <code>optional .sorts.mediawiki.Page.Revision.Contributor contributor = 3;</code>
       */
      public boolean hasContributor() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .sorts.mediawiki.Page.Revision.Contributor contributor = 3;</code>
       */
      public sorts.mediawiki.MediawikiPage.Page.Revision.Contributor getContributor() {
        return contributor_;
      }
      /**
       * <code>optional .sorts.mediawiki.Page.Revision.Contributor contributor = 3;</code>
       */
      public sorts.mediawiki.MediawikiPage.Page.Revision.ContributorOrBuilder getContributorOrBuilder() {
        return contributor_;
      }

      // optional bool minor = 4;
      public static final int MINOR_FIELD_NUMBER = 4;
      private boolean minor_;
      /**
       * <code>optional bool minor = 4;</code>
       */
      public boolean hasMinor() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional bool minor = 4;</code>
       */
      public boolean getMinor() {
        return minor_;
      }

      private void initFields() {
        id_ = 0L;
        timestamp_ = "";
        contributor_ = sorts.mediawiki.MediawikiPage.Page.Revision.Contributor.getDefaultInstance();
        minor_ = false;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        if (!hasId()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasTimestamp()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeUInt64(1, id_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBytes(2, getTimestampBytes());
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeMessage(3, contributor_);
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          output.writeBool(4, minor_);
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt64Size(1, id_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, getTimestampBytes());
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(3, contributor_);
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBoolSize(4, minor_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static sorts.mediawiki.MediawikiPage.Page.Revision parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static sorts.mediawiki.MediawikiPage.Page.Revision parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static sorts.mediawiki.MediawikiPage.Page.Revision parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static sorts.mediawiki.MediawikiPage.Page.Revision parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static sorts.mediawiki.MediawikiPage.Page.Revision parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static sorts.mediawiki.MediawikiPage.Page.Revision parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static sorts.mediawiki.MediawikiPage.Page.Revision parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static sorts.mediawiki.MediawikiPage.Page.Revision parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static sorts.mediawiki.MediawikiPage.Page.Revision parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static sorts.mediawiki.MediawikiPage.Page.Revision parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(sorts.mediawiki.MediawikiPage.Page.Revision prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code sorts.mediawiki.Page.Revision}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements sorts.mediawiki.MediawikiPage.Page.RevisionOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return sorts.mediawiki.MediawikiPage.internal_static_sorts_mediawiki_Page_Revision_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return sorts.mediawiki.MediawikiPage.internal_static_sorts_mediawiki_Page_Revision_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  sorts.mediawiki.MediawikiPage.Page.Revision.class, sorts.mediawiki.MediawikiPage.Page.Revision.Builder.class);
        }

        // Construct using sorts.mediawiki.MediawikiPage.Page.Revision.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
            getContributorFieldBuilder();
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          id_ = 0L;
          bitField0_ = (bitField0_ & ~0x00000001);
          timestamp_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          if (contributorBuilder_ == null) {
            contributor_ = sorts.mediawiki.MediawikiPage.Page.Revision.Contributor.getDefaultInstance();
          } else {
            contributorBuilder_.clear();
          }
          bitField0_ = (bitField0_ & ~0x00000004);
          minor_ = false;
          bitField0_ = (bitField0_ & ~0x00000008);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return sorts.mediawiki.MediawikiPage.internal_static_sorts_mediawiki_Page_Revision_descriptor;
        }

        public sorts.mediawiki.MediawikiPage.Page.Revision getDefaultInstanceForType() {
          return sorts.mediawiki.MediawikiPage.Page.Revision.getDefaultInstance();
        }

        public sorts.mediawiki.MediawikiPage.Page.Revision build() {
          sorts.mediawiki.MediawikiPage.Page.Revision result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public sorts.mediawiki.MediawikiPage.Page.Revision buildPartial() {
          sorts.mediawiki.MediawikiPage.Page.Revision result = new sorts.mediawiki.MediawikiPage.Page.Revision(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.id_ = id_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.timestamp_ = timestamp_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          if (contributorBuilder_ == null) {
            result.contributor_ = contributor_;
          } else {
            result.contributor_ = contributorBuilder_.build();
          }
          if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
            to_bitField0_ |= 0x00000008;
          }
          result.minor_ = minor_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof sorts.mediawiki.MediawikiPage.Page.Revision) {
            return mergeFrom((sorts.mediawiki.MediawikiPage.Page.Revision)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(sorts.mediawiki.MediawikiPage.Page.Revision other) {
          if (other == sorts.mediawiki.MediawikiPage.Page.Revision.getDefaultInstance()) return this;
          if (other.hasId()) {
            setId(other.getId());
          }
          if (other.hasTimestamp()) {
            bitField0_ |= 0x00000002;
            timestamp_ = other.timestamp_;
            onChanged();
          }
          if (other.hasContributor()) {
            mergeContributor(other.getContributor());
          }
          if (other.hasMinor()) {
            setMinor(other.getMinor());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasId()) {
            
            return false;
          }
          if (!hasTimestamp()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          sorts.mediawiki.MediawikiPage.Page.Revision parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (sorts.mediawiki.MediawikiPage.Page.Revision) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // required uint64 id = 1;
        private long id_ ;
        /**
         * <code>required uint64 id = 1;</code>
         */
        public boolean hasId() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required uint64 id = 1;</code>
         */
        public long getId() {
          return id_;
        }
        /**
         * <code>required uint64 id = 1;</code>
         */
        public Builder setId(long value) {
          bitField0_ |= 0x00000001;
          id_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required uint64 id = 1;</code>
         */
        public Builder clearId() {
          bitField0_ = (bitField0_ & ~0x00000001);
          id_ = 0L;
          onChanged();
          return this;
        }

        // required string timestamp = 2;
        private java.lang.Object timestamp_ = "";
        /**
         * <code>required string timestamp = 2;</code>
         */
        public boolean hasTimestamp() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required string timestamp = 2;</code>
         */
        public java.lang.String getTimestamp() {
          java.lang.Object ref = timestamp_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            timestamp_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string timestamp = 2;</code>
         */
        public com.google.protobuf.ByteString
            getTimestampBytes() {
          java.lang.Object ref = timestamp_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            timestamp_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string timestamp = 2;</code>
         */
        public Builder setTimestamp(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          timestamp_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string timestamp = 2;</code>
         */
        public Builder clearTimestamp() {
          bitField0_ = (bitField0_ & ~0x00000002);
          timestamp_ = getDefaultInstance().getTimestamp();
          onChanged();
          return this;
        }
        /**
         * <code>required string timestamp = 2;</code>
         */
        public Builder setTimestampBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          timestamp_ = value;
          onChanged();
          return this;
        }

        // optional .sorts.mediawiki.Page.Revision.Contributor contributor = 3;
        private sorts.mediawiki.MediawikiPage.Page.Revision.Contributor contributor_ = sorts.mediawiki.MediawikiPage.Page.Revision.Contributor.getDefaultInstance();
        private com.google.protobuf.SingleFieldBuilder<
            sorts.mediawiki.MediawikiPage.Page.Revision.Contributor, sorts.mediawiki.MediawikiPage.Page.Revision.Contributor.Builder, sorts.mediawiki.MediawikiPage.Page.Revision.ContributorOrBuilder> contributorBuilder_;
        /**
         * <code>optional .sorts.mediawiki.Page.Revision.Contributor contributor = 3;</code>
         */
        public boolean hasContributor() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        /**
         * <code>optional .sorts.mediawiki.Page.Revision.Contributor contributor = 3;</code>
         */
        public sorts.mediawiki.MediawikiPage.Page.Revision.Contributor getContributor() {
          if (contributorBuilder_ == null) {
            return contributor_;
          } else {
            return contributorBuilder_.getMessage();
          }
        }
        /**
         * <code>optional .sorts.mediawiki.Page.Revision.Contributor contributor = 3;</code>
         */
        public Builder setContributor(sorts.mediawiki.MediawikiPage.Page.Revision.Contributor value) {
          if (contributorBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            contributor_ = value;
            onChanged();
          } else {
            contributorBuilder_.setMessage(value);
          }
          bitField0_ |= 0x00000004;
          return this;
        }
        /**
         * <code>optional .sorts.mediawiki.Page.Revision.Contributor contributor = 3;</code>
         */
        public Builder setContributor(
            sorts.mediawiki.MediawikiPage.Page.Revision.Contributor.Builder builderForValue) {
          if (contributorBuilder_ == null) {
            contributor_ = builderForValue.build();
            onChanged();
          } else {
            contributorBuilder_.setMessage(builderForValue.build());
          }
          bitField0_ |= 0x00000004;
          return this;
        }
        /**
         * <code>optional .sorts.mediawiki.Page.Revision.Contributor contributor = 3;</code>
         */
        public Builder mergeContributor(sorts.mediawiki.MediawikiPage.Page.Revision.Contributor value) {
          if (contributorBuilder_ == null) {
            if (((bitField0_ & 0x00000004) == 0x00000004) &&
                contributor_ != sorts.mediawiki.MediawikiPage.Page.Revision.Contributor.getDefaultInstance()) {
              contributor_ =
                sorts.mediawiki.MediawikiPage.Page.Revision.Contributor.newBuilder(contributor_).mergeFrom(value).buildPartial();
            } else {
              contributor_ = value;
            }
            onChanged();
          } else {
            contributorBuilder_.mergeFrom(value);
          }
          bitField0_ |= 0x00000004;
          return this;
        }
        /**
         * <code>optional .sorts.mediawiki.Page.Revision.Contributor contributor = 3;</code>
         */
        public Builder clearContributor() {
          if (contributorBuilder_ == null) {
            contributor_ = sorts.mediawiki.MediawikiPage.Page.Revision.Contributor.getDefaultInstance();
            onChanged();
          } else {
            contributorBuilder_.clear();
          }
          bitField0_ = (bitField0_ & ~0x00000004);
          return this;
        }
        /**
         * <code>optional .sorts.mediawiki.Page.Revision.Contributor contributor = 3;</code>
         */
        public sorts.mediawiki.MediawikiPage.Page.Revision.Contributor.Builder getContributorBuilder() {
          bitField0_ |= 0x00000004;
          onChanged();
          return getContributorFieldBuilder().getBuilder();
        }
        /**
         * <code>optional .sorts.mediawiki.Page.Revision.Contributor contributor = 3;</code>
         */
        public sorts.mediawiki.MediawikiPage.Page.Revision.ContributorOrBuilder getContributorOrBuilder() {
          if (contributorBuilder_ != null) {
            return contributorBuilder_.getMessageOrBuilder();
          } else {
            return contributor_;
          }
        }
        /**
         * <code>optional .sorts.mediawiki.Page.Revision.Contributor contributor = 3;</code>
         */
        private com.google.protobuf.SingleFieldBuilder<
            sorts.mediawiki.MediawikiPage.Page.Revision.Contributor, sorts.mediawiki.MediawikiPage.Page.Revision.Contributor.Builder, sorts.mediawiki.MediawikiPage.Page.Revision.ContributorOrBuilder> 
            getContributorFieldBuilder() {
          if (contributorBuilder_ == null) {
            contributorBuilder_ = new com.google.protobuf.SingleFieldBuilder<
                sorts.mediawiki.MediawikiPage.Page.Revision.Contributor, sorts.mediawiki.MediawikiPage.Page.Revision.Contributor.Builder, sorts.mediawiki.MediawikiPage.Page.Revision.ContributorOrBuilder>(
                    contributor_,
                    getParentForChildren(),
                    isClean());
            contributor_ = null;
          }
          return contributorBuilder_;
        }

        // optional bool minor = 4;
        private boolean minor_ ;
        /**
         * <code>optional bool minor = 4;</code>
         */
        public boolean hasMinor() {
          return ((bitField0_ & 0x00000008) == 0x00000008);
        }
        /**
         * <code>optional bool minor = 4;</code>
         */
        public boolean getMinor() {
          return minor_;
        }
        /**
         * <code>optional bool minor = 4;</code>
         */
        public Builder setMinor(boolean value) {
          bitField0_ |= 0x00000008;
          minor_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional bool minor = 4;</code>
         */
        public Builder clearMinor() {
          bitField0_ = (bitField0_ & ~0x00000008);
          minor_ = false;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:sorts.mediawiki.Page.Revision)
      }

      static {
        defaultInstance = new Revision(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:sorts.mediawiki.Page.Revision)
    }

    private int bitField0_;
    // required uint64 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>required uint64 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }

    // optional .sorts.mediawiki.Page.Revision revision = 2;
    public static final int REVISION_FIELD_NUMBER = 2;
    private sorts.mediawiki.MediawikiPage.Page.Revision revision_;
    /**
     * <code>optional .sorts.mediawiki.Page.Revision revision = 2;</code>
     */
    public boolean hasRevision() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .sorts.mediawiki.Page.Revision revision = 2;</code>
     */
    public sorts.mediawiki.MediawikiPage.Page.Revision getRevision() {
      return revision_;
    }
    /**
     * <code>optional .sorts.mediawiki.Page.Revision revision = 2;</code>
     */
    public sorts.mediawiki.MediawikiPage.Page.RevisionOrBuilder getRevisionOrBuilder() {
      return revision_;
    }

    private void initFields() {
      id_ = 0L;
      revision_ = sorts.mediawiki.MediawikiPage.Page.Revision.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasRevision()) {
        if (!getRevision().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt64(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, revision_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, revision_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static sorts.mediawiki.MediawikiPage.Page parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sorts.mediawiki.MediawikiPage.Page parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sorts.mediawiki.MediawikiPage.Page parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sorts.mediawiki.MediawikiPage.Page parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sorts.mediawiki.MediawikiPage.Page parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static sorts.mediawiki.MediawikiPage.Page parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static sorts.mediawiki.MediawikiPage.Page parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static sorts.mediawiki.MediawikiPage.Page parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static sorts.mediawiki.MediawikiPage.Page parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static sorts.mediawiki.MediawikiPage.Page parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(sorts.mediawiki.MediawikiPage.Page prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code sorts.mediawiki.Page}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements sorts.mediawiki.MediawikiPage.PageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return sorts.mediawiki.MediawikiPage.internal_static_sorts_mediawiki_Page_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return sorts.mediawiki.MediawikiPage.internal_static_sorts_mediawiki_Page_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                sorts.mediawiki.MediawikiPage.Page.class, sorts.mediawiki.MediawikiPage.Page.Builder.class);
      }

      // Construct using sorts.mediawiki.MediawikiPage.Page.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getRevisionFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (revisionBuilder_ == null) {
          revision_ = sorts.mediawiki.MediawikiPage.Page.Revision.getDefaultInstance();
        } else {
          revisionBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return sorts.mediawiki.MediawikiPage.internal_static_sorts_mediawiki_Page_descriptor;
      }

      public sorts.mediawiki.MediawikiPage.Page getDefaultInstanceForType() {
        return sorts.mediawiki.MediawikiPage.Page.getDefaultInstance();
      }

      public sorts.mediawiki.MediawikiPage.Page build() {
        sorts.mediawiki.MediawikiPage.Page result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public sorts.mediawiki.MediawikiPage.Page buildPartial() {
        sorts.mediawiki.MediawikiPage.Page result = new sorts.mediawiki.MediawikiPage.Page(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (revisionBuilder_ == null) {
          result.revision_ = revision_;
        } else {
          result.revision_ = revisionBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof sorts.mediawiki.MediawikiPage.Page) {
          return mergeFrom((sorts.mediawiki.MediawikiPage.Page)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(sorts.mediawiki.MediawikiPage.Page other) {
        if (other == sorts.mediawiki.MediawikiPage.Page.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasRevision()) {
          mergeRevision(other.getRevision());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (hasRevision()) {
          if (!getRevision().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        sorts.mediawiki.MediawikiPage.Page parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (sorts.mediawiki.MediawikiPage.Page) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required uint64 id = 1;
      private long id_ ;
      /**
       * <code>required uint64 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint64 id = 1;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>required uint64 id = 1;</code>
       */
      public Builder setId(long value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint64 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }

      // optional .sorts.mediawiki.Page.Revision revision = 2;
      private sorts.mediawiki.MediawikiPage.Page.Revision revision_ = sorts.mediawiki.MediawikiPage.Page.Revision.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          sorts.mediawiki.MediawikiPage.Page.Revision, sorts.mediawiki.MediawikiPage.Page.Revision.Builder, sorts.mediawiki.MediawikiPage.Page.RevisionOrBuilder> revisionBuilder_;
      /**
       * <code>optional .sorts.mediawiki.Page.Revision revision = 2;</code>
       */
      public boolean hasRevision() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .sorts.mediawiki.Page.Revision revision = 2;</code>
       */
      public sorts.mediawiki.MediawikiPage.Page.Revision getRevision() {
        if (revisionBuilder_ == null) {
          return revision_;
        } else {
          return revisionBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .sorts.mediawiki.Page.Revision revision = 2;</code>
       */
      public Builder setRevision(sorts.mediawiki.MediawikiPage.Page.Revision value) {
        if (revisionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          revision_ = value;
          onChanged();
        } else {
          revisionBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .sorts.mediawiki.Page.Revision revision = 2;</code>
       */
      public Builder setRevision(
          sorts.mediawiki.MediawikiPage.Page.Revision.Builder builderForValue) {
        if (revisionBuilder_ == null) {
          revision_ = builderForValue.build();
          onChanged();
        } else {
          revisionBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .sorts.mediawiki.Page.Revision revision = 2;</code>
       */
      public Builder mergeRevision(sorts.mediawiki.MediawikiPage.Page.Revision value) {
        if (revisionBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              revision_ != sorts.mediawiki.MediawikiPage.Page.Revision.getDefaultInstance()) {
            revision_ =
              sorts.mediawiki.MediawikiPage.Page.Revision.newBuilder(revision_).mergeFrom(value).buildPartial();
          } else {
            revision_ = value;
          }
          onChanged();
        } else {
          revisionBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .sorts.mediawiki.Page.Revision revision = 2;</code>
       */
      public Builder clearRevision() {
        if (revisionBuilder_ == null) {
          revision_ = sorts.mediawiki.MediawikiPage.Page.Revision.getDefaultInstance();
          onChanged();
        } else {
          revisionBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .sorts.mediawiki.Page.Revision revision = 2;</code>
       */
      public sorts.mediawiki.MediawikiPage.Page.Revision.Builder getRevisionBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getRevisionFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .sorts.mediawiki.Page.Revision revision = 2;</code>
       */
      public sorts.mediawiki.MediawikiPage.Page.RevisionOrBuilder getRevisionOrBuilder() {
        if (revisionBuilder_ != null) {
          return revisionBuilder_.getMessageOrBuilder();
        } else {
          return revision_;
        }
      }
      /**
       * <code>optional .sorts.mediawiki.Page.Revision revision = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          sorts.mediawiki.MediawikiPage.Page.Revision, sorts.mediawiki.MediawikiPage.Page.Revision.Builder, sorts.mediawiki.MediawikiPage.Page.RevisionOrBuilder> 
          getRevisionFieldBuilder() {
        if (revisionBuilder_ == null) {
          revisionBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              sorts.mediawiki.MediawikiPage.Page.Revision, sorts.mediawiki.MediawikiPage.Page.Revision.Builder, sorts.mediawiki.MediawikiPage.Page.RevisionOrBuilder>(
                  revision_,
                  getParentForChildren(),
                  isClean());
          revision_ = null;
        }
        return revisionBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:sorts.mediawiki.Page)
    }

    static {
      defaultInstance = new Page(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:sorts.mediawiki.Page)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_sorts_mediawiki_Page_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_sorts_mediawiki_Page_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_sorts_mediawiki_Page_Revision_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_sorts_mediawiki_Page_Revision_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_sorts_mediawiki_Page_Revision_Contributor_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_sorts_mediawiki_Page_Revision_Contributor_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\npage.proto\022\017sorts.mediawiki\"\355\001\n\004Page\022\n" +
      "\n\002id\030\001 \002(\004\0220\n\010revision\030\002 \001(\0132\036.sorts.med" +
      "iawiki.Page.Revision\032\246\001\n\010Revision\022\n\n\002id\030" +
      "\001 \002(\004\022\021\n\ttimestamp\030\002 \002(\t\022?\n\013contributor\030" +
      "\003 \001(\0132*.sorts.mediawiki.Page.Revision.Co" +
      "ntributor\022\r\n\005minor\030\004 \001(\010\032+\n\013Contributor\022" +
      "\020\n\010username\030\001 \001(\t\022\n\n\002id\030\002 \001(\004B\021B\rMediawi" +
      "kiPageH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_sorts_mediawiki_Page_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_sorts_mediawiki_Page_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_sorts_mediawiki_Page_descriptor,
              new java.lang.String[] { "Id", "Revision", });
          internal_static_sorts_mediawiki_Page_Revision_descriptor =
            internal_static_sorts_mediawiki_Page_descriptor.getNestedTypes().get(0);
          internal_static_sorts_mediawiki_Page_Revision_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_sorts_mediawiki_Page_Revision_descriptor,
              new java.lang.String[] { "Id", "Timestamp", "Contributor", "Minor", });
          internal_static_sorts_mediawiki_Page_Revision_Contributor_descriptor =
            internal_static_sorts_mediawiki_Page_Revision_descriptor.getNestedTypes().get(0);
          internal_static_sorts_mediawiki_Page_Revision_Contributor_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_sorts_mediawiki_Page_Revision_Contributor_descriptor,
              new java.lang.String[] { "Username", "Id", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
