// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: store.proto

package cosmos.protobuf;

public final class StoreProtobuf {
  private StoreProtobuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code cosmos.protobuf.Order}
   */
  public enum Order
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>ASCENDING = 1;</code>
     */
    ASCENDING(0, 1),
    /**
     * <code>DESCENDING = 2;</code>
     */
    DESCENDING(1, 2),
    ;

    /**
     * <code>ASCENDING = 1;</code>
     */
    public static final int ASCENDING_VALUE = 1;
    /**
     * <code>DESCENDING = 2;</code>
     */
    public static final int DESCENDING_VALUE = 2;


    public final int getNumber() { return value; }

    public static Order valueOf(int value) {
      switch (value) {
        case 1: return ASCENDING;
        case 2: return DESCENDING;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Order>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<Order>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Order>() {
            public Order findValueByNumber(int number) {
              return Order.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return cosmos.protobuf.StoreProtobuf.getDescriptor().getEnumTypes().get(0);
    }

    private static final Order[] VALUES = values();

    public static Order valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private Order(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:cosmos.protobuf.Order)
  }

  /**
   * Protobuf enum {@code cosmos.protobuf.IndexSpec}
   */
  public enum IndexSpec
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>IDENTITY = 1;</code>
     */
    IDENTITY(0, 1),
    /**
     * <code>ASCENDING_IDENTITY = 2;</code>
     */
    ASCENDING_IDENTITY(1, 2),
    /**
     * <code>DESCENDING_IDENTITY = 3;</code>
     */
    DESCENDING_IDENTITY(2, 3),
    /**
     * <code>OTHER = 4;</code>
     */
    OTHER(3, 4),
    ;

    /**
     * <code>IDENTITY = 1;</code>
     */
    public static final int IDENTITY_VALUE = 1;
    /**
     * <code>ASCENDING_IDENTITY = 2;</code>
     */
    public static final int ASCENDING_IDENTITY_VALUE = 2;
    /**
     * <code>DESCENDING_IDENTITY = 3;</code>
     */
    public static final int DESCENDING_IDENTITY_VALUE = 3;
    /**
     * <code>OTHER = 4;</code>
     */
    public static final int OTHER_VALUE = 4;


    public final int getNumber() { return value; }

    public static IndexSpec valueOf(int value) {
      switch (value) {
        case 1: return IDENTITY;
        case 2: return ASCENDING_IDENTITY;
        case 3: return DESCENDING_IDENTITY;
        case 4: return OTHER;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<IndexSpec>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<IndexSpec>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<IndexSpec>() {
            public IndexSpec findValueByNumber(int number) {
              return IndexSpec.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return cosmos.protobuf.StoreProtobuf.getDescriptor().getEnumTypes().get(1);
    }

    private static final IndexSpec[] VALUES = values();

    public static IndexSpec valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private IndexSpec(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:cosmos.protobuf.IndexSpec)
  }

  public interface IndexOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string column = 1;
    /**
     * <code>required string column = 1;</code>
     */
    boolean hasColumn();
    /**
     * <code>required string column = 1;</code>
     */
    java.lang.String getColumn();
    /**
     * <code>required string column = 1;</code>
     */
    com.google.protobuf.ByteString
        getColumnBytes();

    // required .cosmos.protobuf.Order order = 2;
    /**
     * <code>required .cosmos.protobuf.Order order = 2;</code>
     */
    boolean hasOrder();
    /**
     * <code>required .cosmos.protobuf.Order order = 2;</code>
     */
    cosmos.protobuf.StoreProtobuf.Order getOrder();

    // required string type = 3;
    /**
     * <code>required string type = 3;</code>
     */
    boolean hasType();
    /**
     * <code>required string type = 3;</code>
     */
    java.lang.String getType();
    /**
     * <code>required string type = 3;</code>
     */
    com.google.protobuf.ByteString
        getTypeBytes();
  }
  /**
   * Protobuf type {@code cosmos.protobuf.Index}
   */
  public static final class Index extends
      com.google.protobuf.GeneratedMessage
      implements IndexOrBuilder {
    // Use Index.newBuilder() to construct.
    private Index(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Index(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Index defaultInstance;
    public static Index getDefaultInstance() {
      return defaultInstance;
    }

    public Index getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Index(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              column_ = input.readBytes();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              cosmos.protobuf.StoreProtobuf.Order value = cosmos.protobuf.StoreProtobuf.Order.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                order_ = value;
              }
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              type_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cosmos.protobuf.StoreProtobuf.internal_static_cosmos_protobuf_Index_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cosmos.protobuf.StoreProtobuf.internal_static_cosmos_protobuf_Index_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cosmos.protobuf.StoreProtobuf.Index.class, cosmos.protobuf.StoreProtobuf.Index.Builder.class);
    }

    public static com.google.protobuf.Parser<Index> PARSER =
        new com.google.protobuf.AbstractParser<Index>() {
      public Index parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Index(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Index> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string column = 1;
    public static final int COLUMN_FIELD_NUMBER = 1;
    private java.lang.Object column_;
    /**
     * <code>required string column = 1;</code>
     */
    public boolean hasColumn() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string column = 1;</code>
     */
    public java.lang.String getColumn() {
      java.lang.Object ref = column_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          column_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string column = 1;</code>
     */
    public com.google.protobuf.ByteString
        getColumnBytes() {
      java.lang.Object ref = column_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        column_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required .cosmos.protobuf.Order order = 2;
    public static final int ORDER_FIELD_NUMBER = 2;
    private cosmos.protobuf.StoreProtobuf.Order order_;
    /**
     * <code>required .cosmos.protobuf.Order order = 2;</code>
     */
    public boolean hasOrder() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .cosmos.protobuf.Order order = 2;</code>
     */
    public cosmos.protobuf.StoreProtobuf.Order getOrder() {
      return order_;
    }

    // required string type = 3;
    public static final int TYPE_FIELD_NUMBER = 3;
    private java.lang.Object type_;
    /**
     * <code>required string type = 3;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string type = 3;</code>
     */
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          type_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string type = 3;</code>
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      column_ = "";
      order_ = cosmos.protobuf.StoreProtobuf.Order.ASCENDING;
      type_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasColumn()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasOrder()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getColumnBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, order_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getTypeBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getColumnBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, order_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getTypeBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static cosmos.protobuf.StoreProtobuf.Index parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cosmos.protobuf.StoreProtobuf.Index parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cosmos.protobuf.StoreProtobuf.Index parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cosmos.protobuf.StoreProtobuf.Index parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cosmos.protobuf.StoreProtobuf.Index parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cosmos.protobuf.StoreProtobuf.Index parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static cosmos.protobuf.StoreProtobuf.Index parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static cosmos.protobuf.StoreProtobuf.Index parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static cosmos.protobuf.StoreProtobuf.Index parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cosmos.protobuf.StoreProtobuf.Index parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(cosmos.protobuf.StoreProtobuf.Index prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cosmos.protobuf.Index}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements cosmos.protobuf.StoreProtobuf.IndexOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cosmos.protobuf.StoreProtobuf.internal_static_cosmos_protobuf_Index_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cosmos.protobuf.StoreProtobuf.internal_static_cosmos_protobuf_Index_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cosmos.protobuf.StoreProtobuf.Index.class, cosmos.protobuf.StoreProtobuf.Index.Builder.class);
      }

      // Construct using cosmos.protobuf.StoreProtobuf.Index.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        column_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        order_ = cosmos.protobuf.StoreProtobuf.Order.ASCENDING;
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cosmos.protobuf.StoreProtobuf.internal_static_cosmos_protobuf_Index_descriptor;
      }

      public cosmos.protobuf.StoreProtobuf.Index getDefaultInstanceForType() {
        return cosmos.protobuf.StoreProtobuf.Index.getDefaultInstance();
      }

      public cosmos.protobuf.StoreProtobuf.Index build() {
        cosmos.protobuf.StoreProtobuf.Index result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cosmos.protobuf.StoreProtobuf.Index buildPartial() {
        cosmos.protobuf.StoreProtobuf.Index result = new cosmos.protobuf.StoreProtobuf.Index(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.column_ = column_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.order_ = order_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.type_ = type_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cosmos.protobuf.StoreProtobuf.Index) {
          return mergeFrom((cosmos.protobuf.StoreProtobuf.Index)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cosmos.protobuf.StoreProtobuf.Index other) {
        if (other == cosmos.protobuf.StoreProtobuf.Index.getDefaultInstance()) return this;
        if (other.hasColumn()) {
          bitField0_ |= 0x00000001;
          column_ = other.column_;
          onChanged();
        }
        if (other.hasOrder()) {
          setOrder(other.getOrder());
        }
        if (other.hasType()) {
          bitField0_ |= 0x00000004;
          type_ = other.type_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasColumn()) {
          
          return false;
        }
        if (!hasOrder()) {
          
          return false;
        }
        if (!hasType()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cosmos.protobuf.StoreProtobuf.Index parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cosmos.protobuf.StoreProtobuf.Index) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string column = 1;
      private java.lang.Object column_ = "";
      /**
       * <code>required string column = 1;</code>
       */
      public boolean hasColumn() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string column = 1;</code>
       */
      public java.lang.String getColumn() {
        java.lang.Object ref = column_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          column_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string column = 1;</code>
       */
      public com.google.protobuf.ByteString
          getColumnBytes() {
        java.lang.Object ref = column_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          column_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string column = 1;</code>
       */
      public Builder setColumn(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        column_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string column = 1;</code>
       */
      public Builder clearColumn() {
        bitField0_ = (bitField0_ & ~0x00000001);
        column_ = getDefaultInstance().getColumn();
        onChanged();
        return this;
      }
      /**
       * <code>required string column = 1;</code>
       */
      public Builder setColumnBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        column_ = value;
        onChanged();
        return this;
      }

      // required .cosmos.protobuf.Order order = 2;
      private cosmos.protobuf.StoreProtobuf.Order order_ = cosmos.protobuf.StoreProtobuf.Order.ASCENDING;
      /**
       * <code>required .cosmos.protobuf.Order order = 2;</code>
       */
      public boolean hasOrder() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .cosmos.protobuf.Order order = 2;</code>
       */
      public cosmos.protobuf.StoreProtobuf.Order getOrder() {
        return order_;
      }
      /**
       * <code>required .cosmos.protobuf.Order order = 2;</code>
       */
      public Builder setOrder(cosmos.protobuf.StoreProtobuf.Order value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        order_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .cosmos.protobuf.Order order = 2;</code>
       */
      public Builder clearOrder() {
        bitField0_ = (bitField0_ & ~0x00000002);
        order_ = cosmos.protobuf.StoreProtobuf.Order.ASCENDING;
        onChanged();
        return this;
      }

      // required string type = 3;
      private java.lang.Object type_ = "";
      /**
       * <code>required string type = 3;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string type = 3;</code>
       */
      public java.lang.String getType() {
        java.lang.Object ref = type_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          type_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string type = 3;</code>
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        java.lang.Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string type = 3;</code>
       */
      public Builder setType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string type = 3;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        type_ = getDefaultInstance().getType();
        onChanged();
        return this;
      }
      /**
       * <code>required string type = 3;</code>
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        type_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:cosmos.protobuf.Index)
    }

    static {
      defaultInstance = new Index(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:cosmos.protobuf.Index)
  }

  public interface StoreOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string unique_id = 1;
    /**
     * <code>required string unique_id = 1;</code>
     */
    boolean hasUniqueId();
    /**
     * <code>required string unique_id = 1;</code>
     */
    java.lang.String getUniqueId();
    /**
     * <code>required string unique_id = 1;</code>
     */
    com.google.protobuf.ByteString
        getUniqueIdBytes();

    // required string auths = 2;
    /**
     * <code>required string auths = 2;</code>
     */
    boolean hasAuths();
    /**
     * <code>required string auths = 2;</code>
     */
    java.lang.String getAuths();
    /**
     * <code>required string auths = 2;</code>
     */
    com.google.protobuf.ByteString
        getAuthsBytes();

    // required string data_table = 3;
    /**
     * <code>required string data_table = 3;</code>
     */
    boolean hasDataTable();
    /**
     * <code>required string data_table = 3;</code>
     */
    java.lang.String getDataTable();
    /**
     * <code>required string data_table = 3;</code>
     */
    com.google.protobuf.ByteString
        getDataTableBytes();

    // required string metadata_table = 4;
    /**
     * <code>required string metadata_table = 4;</code>
     */
    boolean hasMetadataTable();
    /**
     * <code>required string metadata_table = 4;</code>
     */
    java.lang.String getMetadataTable();
    /**
     * <code>required string metadata_table = 4;</code>
     */
    com.google.protobuf.ByteString
        getMetadataTableBytes();

    // required .cosmos.protobuf.IndexSpec index_spec = 5;
    /**
     * <code>required .cosmos.protobuf.IndexSpec index_spec = 5;</code>
     */
    boolean hasIndexSpec();
    /**
     * <code>required .cosmos.protobuf.IndexSpec index_spec = 5;</code>
     */
    cosmos.protobuf.StoreProtobuf.IndexSpec getIndexSpec();

    // repeated .cosmos.protobuf.Index indexes = 6;
    /**
     * <code>repeated .cosmos.protobuf.Index indexes = 6;</code>
     */
    java.util.List<cosmos.protobuf.StoreProtobuf.Index> 
        getIndexesList();
    /**
     * <code>repeated .cosmos.protobuf.Index indexes = 6;</code>
     */
    cosmos.protobuf.StoreProtobuf.Index getIndexes(int index);
    /**
     * <code>repeated .cosmos.protobuf.Index indexes = 6;</code>
     */
    int getIndexesCount();
    /**
     * <code>repeated .cosmos.protobuf.Index indexes = 6;</code>
     */
    java.util.List<? extends cosmos.protobuf.StoreProtobuf.IndexOrBuilder> 
        getIndexesOrBuilderList();
    /**
     * <code>repeated .cosmos.protobuf.Index indexes = 6;</code>
     */
    cosmos.protobuf.StoreProtobuf.IndexOrBuilder getIndexesOrBuilder(
        int index);

    // optional bool lock_on_updates = 7;
    /**
     * <code>optional bool lock_on_updates = 7;</code>
     */
    boolean hasLockOnUpdates();
    /**
     * <code>optional bool lock_on_updates = 7;</code>
     */
    boolean getLockOnUpdates();
  }
  /**
   * Protobuf type {@code cosmos.protobuf.Store}
   */
  public static final class Store extends
      com.google.protobuf.GeneratedMessage
      implements StoreOrBuilder {
    // Use Store.newBuilder() to construct.
    private Store(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Store(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Store defaultInstance;
    public static Store getDefaultInstance() {
      return defaultInstance;
    }

    public Store getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Store(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              uniqueId_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              auths_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              dataTable_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              metadataTable_ = input.readBytes();
              break;
            }
            case 40: {
              int rawValue = input.readEnum();
              cosmos.protobuf.StoreProtobuf.IndexSpec value = cosmos.protobuf.StoreProtobuf.IndexSpec.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(5, rawValue);
              } else {
                bitField0_ |= 0x00000010;
                indexSpec_ = value;
              }
              break;
            }
            case 50: {
              if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
                indexes_ = new java.util.ArrayList<cosmos.protobuf.StoreProtobuf.Index>();
                mutable_bitField0_ |= 0x00000020;
              }
              indexes_.add(input.readMessage(cosmos.protobuf.StoreProtobuf.Index.PARSER, extensionRegistry));
              break;
            }
            case 56: {
              bitField0_ |= 0x00000020;
              lockOnUpdates_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
          indexes_ = java.util.Collections.unmodifiableList(indexes_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cosmos.protobuf.StoreProtobuf.internal_static_cosmos_protobuf_Store_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cosmos.protobuf.StoreProtobuf.internal_static_cosmos_protobuf_Store_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cosmos.protobuf.StoreProtobuf.Store.class, cosmos.protobuf.StoreProtobuf.Store.Builder.class);
    }

    public static com.google.protobuf.Parser<Store> PARSER =
        new com.google.protobuf.AbstractParser<Store>() {
      public Store parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Store(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Store> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string unique_id = 1;
    public static final int UNIQUE_ID_FIELD_NUMBER = 1;
    private java.lang.Object uniqueId_;
    /**
     * <code>required string unique_id = 1;</code>
     */
    public boolean hasUniqueId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string unique_id = 1;</code>
     */
    public java.lang.String getUniqueId() {
      java.lang.Object ref = uniqueId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          uniqueId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string unique_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUniqueIdBytes() {
      java.lang.Object ref = uniqueId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uniqueId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string auths = 2;
    public static final int AUTHS_FIELD_NUMBER = 2;
    private java.lang.Object auths_;
    /**
     * <code>required string auths = 2;</code>
     */
    public boolean hasAuths() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string auths = 2;</code>
     */
    public java.lang.String getAuths() {
      java.lang.Object ref = auths_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          auths_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string auths = 2;</code>
     */
    public com.google.protobuf.ByteString
        getAuthsBytes() {
      java.lang.Object ref = auths_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        auths_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string data_table = 3;
    public static final int DATA_TABLE_FIELD_NUMBER = 3;
    private java.lang.Object dataTable_;
    /**
     * <code>required string data_table = 3;</code>
     */
    public boolean hasDataTable() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string data_table = 3;</code>
     */
    public java.lang.String getDataTable() {
      java.lang.Object ref = dataTable_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          dataTable_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string data_table = 3;</code>
     */
    public com.google.protobuf.ByteString
        getDataTableBytes() {
      java.lang.Object ref = dataTable_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dataTable_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string metadata_table = 4;
    public static final int METADATA_TABLE_FIELD_NUMBER = 4;
    private java.lang.Object metadataTable_;
    /**
     * <code>required string metadata_table = 4;</code>
     */
    public boolean hasMetadataTable() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string metadata_table = 4;</code>
     */
    public java.lang.String getMetadataTable() {
      java.lang.Object ref = metadataTable_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          metadataTable_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string metadata_table = 4;</code>
     */
    public com.google.protobuf.ByteString
        getMetadataTableBytes() {
      java.lang.Object ref = metadataTable_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        metadataTable_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required .cosmos.protobuf.IndexSpec index_spec = 5;
    public static final int INDEX_SPEC_FIELD_NUMBER = 5;
    private cosmos.protobuf.StoreProtobuf.IndexSpec indexSpec_;
    /**
     * <code>required .cosmos.protobuf.IndexSpec index_spec = 5;</code>
     */
    public boolean hasIndexSpec() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required .cosmos.protobuf.IndexSpec index_spec = 5;</code>
     */
    public cosmos.protobuf.StoreProtobuf.IndexSpec getIndexSpec() {
      return indexSpec_;
    }

    // repeated .cosmos.protobuf.Index indexes = 6;
    public static final int INDEXES_FIELD_NUMBER = 6;
    private java.util.List<cosmos.protobuf.StoreProtobuf.Index> indexes_;
    /**
     * <code>repeated .cosmos.protobuf.Index indexes = 6;</code>
     */
    public java.util.List<cosmos.protobuf.StoreProtobuf.Index> getIndexesList() {
      return indexes_;
    }
    /**
     * <code>repeated .cosmos.protobuf.Index indexes = 6;</code>
     */
    public java.util.List<? extends cosmos.protobuf.StoreProtobuf.IndexOrBuilder> 
        getIndexesOrBuilderList() {
      return indexes_;
    }
    /**
     * <code>repeated .cosmos.protobuf.Index indexes = 6;</code>
     */
    public int getIndexesCount() {
      return indexes_.size();
    }
    /**
     * <code>repeated .cosmos.protobuf.Index indexes = 6;</code>
     */
    public cosmos.protobuf.StoreProtobuf.Index getIndexes(int index) {
      return indexes_.get(index);
    }
    /**
     * <code>repeated .cosmos.protobuf.Index indexes = 6;</code>
     */
    public cosmos.protobuf.StoreProtobuf.IndexOrBuilder getIndexesOrBuilder(
        int index) {
      return indexes_.get(index);
    }

    // optional bool lock_on_updates = 7;
    public static final int LOCK_ON_UPDATES_FIELD_NUMBER = 7;
    private boolean lockOnUpdates_;
    /**
     * <code>optional bool lock_on_updates = 7;</code>
     */
    public boolean hasLockOnUpdates() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional bool lock_on_updates = 7;</code>
     */
    public boolean getLockOnUpdates() {
      return lockOnUpdates_;
    }

    private void initFields() {
      uniqueId_ = "";
      auths_ = "";
      dataTable_ = "";
      metadataTable_ = "";
      indexSpec_ = cosmos.protobuf.StoreProtobuf.IndexSpec.IDENTITY;
      indexes_ = java.util.Collections.emptyList();
      lockOnUpdates_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasUniqueId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAuths()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDataTable()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMetadataTable()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIndexSpec()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getIndexesCount(); i++) {
        if (!getIndexes(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getUniqueIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getAuthsBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getDataTableBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getMetadataTableBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeEnum(5, indexSpec_.getNumber());
      }
      for (int i = 0; i < indexes_.size(); i++) {
        output.writeMessage(6, indexes_.get(i));
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBool(7, lockOnUpdates_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getUniqueIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getAuthsBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getDataTableBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getMetadataTableBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, indexSpec_.getNumber());
      }
      for (int i = 0; i < indexes_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, indexes_.get(i));
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(7, lockOnUpdates_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static cosmos.protobuf.StoreProtobuf.Store parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cosmos.protobuf.StoreProtobuf.Store parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cosmos.protobuf.StoreProtobuf.Store parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cosmos.protobuf.StoreProtobuf.Store parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cosmos.protobuf.StoreProtobuf.Store parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cosmos.protobuf.StoreProtobuf.Store parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static cosmos.protobuf.StoreProtobuf.Store parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static cosmos.protobuf.StoreProtobuf.Store parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static cosmos.protobuf.StoreProtobuf.Store parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cosmos.protobuf.StoreProtobuf.Store parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(cosmos.protobuf.StoreProtobuf.Store prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cosmos.protobuf.Store}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements cosmos.protobuf.StoreProtobuf.StoreOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cosmos.protobuf.StoreProtobuf.internal_static_cosmos_protobuf_Store_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cosmos.protobuf.StoreProtobuf.internal_static_cosmos_protobuf_Store_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cosmos.protobuf.StoreProtobuf.Store.class, cosmos.protobuf.StoreProtobuf.Store.Builder.class);
      }

      // Construct using cosmos.protobuf.StoreProtobuf.Store.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getIndexesFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        uniqueId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        auths_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        dataTable_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        metadataTable_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        indexSpec_ = cosmos.protobuf.StoreProtobuf.IndexSpec.IDENTITY;
        bitField0_ = (bitField0_ & ~0x00000010);
        if (indexesBuilder_ == null) {
          indexes_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000020);
        } else {
          indexesBuilder_.clear();
        }
        lockOnUpdates_ = false;
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cosmos.protobuf.StoreProtobuf.internal_static_cosmos_protobuf_Store_descriptor;
      }

      public cosmos.protobuf.StoreProtobuf.Store getDefaultInstanceForType() {
        return cosmos.protobuf.StoreProtobuf.Store.getDefaultInstance();
      }

      public cosmos.protobuf.StoreProtobuf.Store build() {
        cosmos.protobuf.StoreProtobuf.Store result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cosmos.protobuf.StoreProtobuf.Store buildPartial() {
        cosmos.protobuf.StoreProtobuf.Store result = new cosmos.protobuf.StoreProtobuf.Store(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.uniqueId_ = uniqueId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.auths_ = auths_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.dataTable_ = dataTable_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.metadataTable_ = metadataTable_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.indexSpec_ = indexSpec_;
        if (indexesBuilder_ == null) {
          if (((bitField0_ & 0x00000020) == 0x00000020)) {
            indexes_ = java.util.Collections.unmodifiableList(indexes_);
            bitField0_ = (bitField0_ & ~0x00000020);
          }
          result.indexes_ = indexes_;
        } else {
          result.indexes_ = indexesBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000020;
        }
        result.lockOnUpdates_ = lockOnUpdates_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cosmos.protobuf.StoreProtobuf.Store) {
          return mergeFrom((cosmos.protobuf.StoreProtobuf.Store)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cosmos.protobuf.StoreProtobuf.Store other) {
        if (other == cosmos.protobuf.StoreProtobuf.Store.getDefaultInstance()) return this;
        if (other.hasUniqueId()) {
          bitField0_ |= 0x00000001;
          uniqueId_ = other.uniqueId_;
          onChanged();
        }
        if (other.hasAuths()) {
          bitField0_ |= 0x00000002;
          auths_ = other.auths_;
          onChanged();
        }
        if (other.hasDataTable()) {
          bitField0_ |= 0x00000004;
          dataTable_ = other.dataTable_;
          onChanged();
        }
        if (other.hasMetadataTable()) {
          bitField0_ |= 0x00000008;
          metadataTable_ = other.metadataTable_;
          onChanged();
        }
        if (other.hasIndexSpec()) {
          setIndexSpec(other.getIndexSpec());
        }
        if (indexesBuilder_ == null) {
          if (!other.indexes_.isEmpty()) {
            if (indexes_.isEmpty()) {
              indexes_ = other.indexes_;
              bitField0_ = (bitField0_ & ~0x00000020);
            } else {
              ensureIndexesIsMutable();
              indexes_.addAll(other.indexes_);
            }
            onChanged();
          }
        } else {
          if (!other.indexes_.isEmpty()) {
            if (indexesBuilder_.isEmpty()) {
              indexesBuilder_.dispose();
              indexesBuilder_ = null;
              indexes_ = other.indexes_;
              bitField0_ = (bitField0_ & ~0x00000020);
              indexesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getIndexesFieldBuilder() : null;
            } else {
              indexesBuilder_.addAllMessages(other.indexes_);
            }
          }
        }
        if (other.hasLockOnUpdates()) {
          setLockOnUpdates(other.getLockOnUpdates());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUniqueId()) {
          
          return false;
        }
        if (!hasAuths()) {
          
          return false;
        }
        if (!hasDataTable()) {
          
          return false;
        }
        if (!hasMetadataTable()) {
          
          return false;
        }
        if (!hasIndexSpec()) {
          
          return false;
        }
        for (int i = 0; i < getIndexesCount(); i++) {
          if (!getIndexes(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cosmos.protobuf.StoreProtobuf.Store parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cosmos.protobuf.StoreProtobuf.Store) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string unique_id = 1;
      private java.lang.Object uniqueId_ = "";
      /**
       * <code>required string unique_id = 1;</code>
       */
      public boolean hasUniqueId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string unique_id = 1;</code>
       */
      public java.lang.String getUniqueId() {
        java.lang.Object ref = uniqueId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          uniqueId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string unique_id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUniqueIdBytes() {
        java.lang.Object ref = uniqueId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uniqueId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string unique_id = 1;</code>
       */
      public Builder setUniqueId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        uniqueId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string unique_id = 1;</code>
       */
      public Builder clearUniqueId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        uniqueId_ = getDefaultInstance().getUniqueId();
        onChanged();
        return this;
      }
      /**
       * <code>required string unique_id = 1;</code>
       */
      public Builder setUniqueIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        uniqueId_ = value;
        onChanged();
        return this;
      }

      // required string auths = 2;
      private java.lang.Object auths_ = "";
      /**
       * <code>required string auths = 2;</code>
       */
      public boolean hasAuths() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string auths = 2;</code>
       */
      public java.lang.String getAuths() {
        java.lang.Object ref = auths_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          auths_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string auths = 2;</code>
       */
      public com.google.protobuf.ByteString
          getAuthsBytes() {
        java.lang.Object ref = auths_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          auths_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string auths = 2;</code>
       */
      public Builder setAuths(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        auths_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string auths = 2;</code>
       */
      public Builder clearAuths() {
        bitField0_ = (bitField0_ & ~0x00000002);
        auths_ = getDefaultInstance().getAuths();
        onChanged();
        return this;
      }
      /**
       * <code>required string auths = 2;</code>
       */
      public Builder setAuthsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        auths_ = value;
        onChanged();
        return this;
      }

      // required string data_table = 3;
      private java.lang.Object dataTable_ = "";
      /**
       * <code>required string data_table = 3;</code>
       */
      public boolean hasDataTable() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string data_table = 3;</code>
       */
      public java.lang.String getDataTable() {
        java.lang.Object ref = dataTable_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          dataTable_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string data_table = 3;</code>
       */
      public com.google.protobuf.ByteString
          getDataTableBytes() {
        java.lang.Object ref = dataTable_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          dataTable_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string data_table = 3;</code>
       */
      public Builder setDataTable(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        dataTable_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string data_table = 3;</code>
       */
      public Builder clearDataTable() {
        bitField0_ = (bitField0_ & ~0x00000004);
        dataTable_ = getDefaultInstance().getDataTable();
        onChanged();
        return this;
      }
      /**
       * <code>required string data_table = 3;</code>
       */
      public Builder setDataTableBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        dataTable_ = value;
        onChanged();
        return this;
      }

      // required string metadata_table = 4;
      private java.lang.Object metadataTable_ = "";
      /**
       * <code>required string metadata_table = 4;</code>
       */
      public boolean hasMetadataTable() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string metadata_table = 4;</code>
       */
      public java.lang.String getMetadataTable() {
        java.lang.Object ref = metadataTable_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          metadataTable_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string metadata_table = 4;</code>
       */
      public com.google.protobuf.ByteString
          getMetadataTableBytes() {
        java.lang.Object ref = metadataTable_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          metadataTable_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string metadata_table = 4;</code>
       */
      public Builder setMetadataTable(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        metadataTable_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string metadata_table = 4;</code>
       */
      public Builder clearMetadataTable() {
        bitField0_ = (bitField0_ & ~0x00000008);
        metadataTable_ = getDefaultInstance().getMetadataTable();
        onChanged();
        return this;
      }
      /**
       * <code>required string metadata_table = 4;</code>
       */
      public Builder setMetadataTableBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        metadataTable_ = value;
        onChanged();
        return this;
      }

      // required .cosmos.protobuf.IndexSpec index_spec = 5;
      private cosmos.protobuf.StoreProtobuf.IndexSpec indexSpec_ = cosmos.protobuf.StoreProtobuf.IndexSpec.IDENTITY;
      /**
       * <code>required .cosmos.protobuf.IndexSpec index_spec = 5;</code>
       */
      public boolean hasIndexSpec() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required .cosmos.protobuf.IndexSpec index_spec = 5;</code>
       */
      public cosmos.protobuf.StoreProtobuf.IndexSpec getIndexSpec() {
        return indexSpec_;
      }
      /**
       * <code>required .cosmos.protobuf.IndexSpec index_spec = 5;</code>
       */
      public Builder setIndexSpec(cosmos.protobuf.StoreProtobuf.IndexSpec value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000010;
        indexSpec_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .cosmos.protobuf.IndexSpec index_spec = 5;</code>
       */
      public Builder clearIndexSpec() {
        bitField0_ = (bitField0_ & ~0x00000010);
        indexSpec_ = cosmos.protobuf.StoreProtobuf.IndexSpec.IDENTITY;
        onChanged();
        return this;
      }

      // repeated .cosmos.protobuf.Index indexes = 6;
      private java.util.List<cosmos.protobuf.StoreProtobuf.Index> indexes_ =
        java.util.Collections.emptyList();
      private void ensureIndexesIsMutable() {
        if (!((bitField0_ & 0x00000020) == 0x00000020)) {
          indexes_ = new java.util.ArrayList<cosmos.protobuf.StoreProtobuf.Index>(indexes_);
          bitField0_ |= 0x00000020;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          cosmos.protobuf.StoreProtobuf.Index, cosmos.protobuf.StoreProtobuf.Index.Builder, cosmos.protobuf.StoreProtobuf.IndexOrBuilder> indexesBuilder_;

      /**
       * <code>repeated .cosmos.protobuf.Index indexes = 6;</code>
       */
      public java.util.List<cosmos.protobuf.StoreProtobuf.Index> getIndexesList() {
        if (indexesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(indexes_);
        } else {
          return indexesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .cosmos.protobuf.Index indexes = 6;</code>
       */
      public int getIndexesCount() {
        if (indexesBuilder_ == null) {
          return indexes_.size();
        } else {
          return indexesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .cosmos.protobuf.Index indexes = 6;</code>
       */
      public cosmos.protobuf.StoreProtobuf.Index getIndexes(int index) {
        if (indexesBuilder_ == null) {
          return indexes_.get(index);
        } else {
          return indexesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .cosmos.protobuf.Index indexes = 6;</code>
       */
      public Builder setIndexes(
          int index, cosmos.protobuf.StoreProtobuf.Index value) {
        if (indexesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureIndexesIsMutable();
          indexes_.set(index, value);
          onChanged();
        } else {
          indexesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .cosmos.protobuf.Index indexes = 6;</code>
       */
      public Builder setIndexes(
          int index, cosmos.protobuf.StoreProtobuf.Index.Builder builderForValue) {
        if (indexesBuilder_ == null) {
          ensureIndexesIsMutable();
          indexes_.set(index, builderForValue.build());
          onChanged();
        } else {
          indexesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .cosmos.protobuf.Index indexes = 6;</code>
       */
      public Builder addIndexes(cosmos.protobuf.StoreProtobuf.Index value) {
        if (indexesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureIndexesIsMutable();
          indexes_.add(value);
          onChanged();
        } else {
          indexesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .cosmos.protobuf.Index indexes = 6;</code>
       */
      public Builder addIndexes(
          int index, cosmos.protobuf.StoreProtobuf.Index value) {
        if (indexesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureIndexesIsMutable();
          indexes_.add(index, value);
          onChanged();
        } else {
          indexesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .cosmos.protobuf.Index indexes = 6;</code>
       */
      public Builder addIndexes(
          cosmos.protobuf.StoreProtobuf.Index.Builder builderForValue) {
        if (indexesBuilder_ == null) {
          ensureIndexesIsMutable();
          indexes_.add(builderForValue.build());
          onChanged();
        } else {
          indexesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .cosmos.protobuf.Index indexes = 6;</code>
       */
      public Builder addIndexes(
          int index, cosmos.protobuf.StoreProtobuf.Index.Builder builderForValue) {
        if (indexesBuilder_ == null) {
          ensureIndexesIsMutable();
          indexes_.add(index, builderForValue.build());
          onChanged();
        } else {
          indexesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .cosmos.protobuf.Index indexes = 6;</code>
       */
      public Builder addAllIndexes(
          java.lang.Iterable<? extends cosmos.protobuf.StoreProtobuf.Index> values) {
        if (indexesBuilder_ == null) {
          ensureIndexesIsMutable();
          super.addAll(values, indexes_);
          onChanged();
        } else {
          indexesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .cosmos.protobuf.Index indexes = 6;</code>
       */
      public Builder clearIndexes() {
        if (indexesBuilder_ == null) {
          indexes_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000020);
          onChanged();
        } else {
          indexesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .cosmos.protobuf.Index indexes = 6;</code>
       */
      public Builder removeIndexes(int index) {
        if (indexesBuilder_ == null) {
          ensureIndexesIsMutable();
          indexes_.remove(index);
          onChanged();
        } else {
          indexesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .cosmos.protobuf.Index indexes = 6;</code>
       */
      public cosmos.protobuf.StoreProtobuf.Index.Builder getIndexesBuilder(
          int index) {
        return getIndexesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .cosmos.protobuf.Index indexes = 6;</code>
       */
      public cosmos.protobuf.StoreProtobuf.IndexOrBuilder getIndexesOrBuilder(
          int index) {
        if (indexesBuilder_ == null) {
          return indexes_.get(index);  } else {
          return indexesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .cosmos.protobuf.Index indexes = 6;</code>
       */
      public java.util.List<? extends cosmos.protobuf.StoreProtobuf.IndexOrBuilder> 
           getIndexesOrBuilderList() {
        if (indexesBuilder_ != null) {
          return indexesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(indexes_);
        }
      }
      /**
       * <code>repeated .cosmos.protobuf.Index indexes = 6;</code>
       */
      public cosmos.protobuf.StoreProtobuf.Index.Builder addIndexesBuilder() {
        return getIndexesFieldBuilder().addBuilder(
            cosmos.protobuf.StoreProtobuf.Index.getDefaultInstance());
      }
      /**
       * <code>repeated .cosmos.protobuf.Index indexes = 6;</code>
       */
      public cosmos.protobuf.StoreProtobuf.Index.Builder addIndexesBuilder(
          int index) {
        return getIndexesFieldBuilder().addBuilder(
            index, cosmos.protobuf.StoreProtobuf.Index.getDefaultInstance());
      }
      /**
       * <code>repeated .cosmos.protobuf.Index indexes = 6;</code>
       */
      public java.util.List<cosmos.protobuf.StoreProtobuf.Index.Builder> 
           getIndexesBuilderList() {
        return getIndexesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          cosmos.protobuf.StoreProtobuf.Index, cosmos.protobuf.StoreProtobuf.Index.Builder, cosmos.protobuf.StoreProtobuf.IndexOrBuilder> 
          getIndexesFieldBuilder() {
        if (indexesBuilder_ == null) {
          indexesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              cosmos.protobuf.StoreProtobuf.Index, cosmos.protobuf.StoreProtobuf.Index.Builder, cosmos.protobuf.StoreProtobuf.IndexOrBuilder>(
                  indexes_,
                  ((bitField0_ & 0x00000020) == 0x00000020),
                  getParentForChildren(),
                  isClean());
          indexes_ = null;
        }
        return indexesBuilder_;
      }

      // optional bool lock_on_updates = 7;
      private boolean lockOnUpdates_ ;
      /**
       * <code>optional bool lock_on_updates = 7;</code>
       */
      public boolean hasLockOnUpdates() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional bool lock_on_updates = 7;</code>
       */
      public boolean getLockOnUpdates() {
        return lockOnUpdates_;
      }
      /**
       * <code>optional bool lock_on_updates = 7;</code>
       */
      public Builder setLockOnUpdates(boolean value) {
        bitField0_ |= 0x00000040;
        lockOnUpdates_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool lock_on_updates = 7;</code>
       */
      public Builder clearLockOnUpdates() {
        bitField0_ = (bitField0_ & ~0x00000040);
        lockOnUpdates_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:cosmos.protobuf.Store)
    }

    static {
      defaultInstance = new Store(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:cosmos.protobuf.Store)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_cosmos_protobuf_Index_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_cosmos_protobuf_Index_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_cosmos_protobuf_Store_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_cosmos_protobuf_Store_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013store.proto\022\017cosmos.protobuf\"L\n\005Index\022" +
      "\016\n\006column\030\001 \002(\t\022%\n\005order\030\002 \002(\0162\026.cosmos." +
      "protobuf.Order\022\014\n\004type\030\003 \002(\t\"\307\001\n\005Store\022\021" +
      "\n\tunique_id\030\001 \002(\t\022\r\n\005auths\030\002 \002(\t\022\022\n\ndata" +
      "_table\030\003 \002(\t\022\026\n\016metadata_table\030\004 \002(\t\022.\n\n" +
      "index_spec\030\005 \002(\0162\032.cosmos.protobuf.Index" +
      "Spec\022\'\n\007indexes\030\006 \003(\0132\026.cosmos.protobuf." +
      "Index\022\027\n\017lock_on_updates\030\007 \001(\010*&\n\005Order\022" +
      "\r\n\tASCENDING\020\001\022\016\n\nDESCENDING\020\002*U\n\tIndexS" +
      "pec\022\014\n\010IDENTITY\020\001\022\026\n\022ASCENDING_IDENTITY\020",
      "\002\022\027\n\023DESCENDING_IDENTITY\020\003\022\t\n\005OTHER\020\004B\021B" +
      "\rStoreProtobufH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_cosmos_protobuf_Index_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_cosmos_protobuf_Index_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_cosmos_protobuf_Index_descriptor,
              new java.lang.String[] { "Column", "Order", "Type", });
          internal_static_cosmos_protobuf_Store_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_cosmos_protobuf_Store_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_cosmos_protobuf_Store_descriptor,
              new java.lang.String[] { "UniqueId", "Auths", "DataTable", "MetadataTable", "IndexSpec", "Indexes", "LockOnUpdates", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
